added arg/tools availability checks, some prints for better usability

diff --git a/helpers/thunar-actions-updater b/helpers/thunar-actions-updater
--- a/helpers/thunar-actions-updater
+++ b/helpers/thunar-actions-updater
@@ -10,9 +10,20 @@
 # Copyright (C) netqa GmbH (http://www.netqa.de)
 # ------------------------------------------------------------------
 
-if [ -z "$1" ]; then
-	printf "ERROR: directory expected.\n"
-fi
+# just for convenience
+die() {
+	printf "%s" "${@+$@$'\n'}" 1>&2 ; exit 1;
+}
+
+# verify some useful tools are present
+XSLT_PROCESSOR=$(command -v xsltproc) || die "ERROR: xsltproc not found. Install libxslt package."
+UUID_GENERATOR=$(command -v uuidgen) || die "ERROR: uuidgen not found. Install e2fsprogs package."
+
+[ -z "$1" ] && die "ERROR: directory containing python virtual environments expected."
+ENV_DIR=$1
+
+THUNAR_ACTIONS_CONFIG="$HOME/.config/Thunar/uca.xml"
+[ -f "$THUNAR_ACTIONS_CONFIG" ] || die "ERROR: no config file for Thunar custom actions found. Check if Thunar is installed correctly."
 
 HEAD=$(cat <<- EOM
 <?xml version="1.0" encoding="UTF-8"?>
@@ -38,9 +49,7 @@ TAIL=$(cat <<- EOM
 \t\t\t<xsl:apply-templates select="@* | node()"/>
 \t\t</xsl:copy>
 \t</xsl:template>
-\t<xsl:comment> remove all old netqa-framework actions</xsl:comment>
 \t<xsl:template match="/actions/action[unique-id[starts-with(., 'netqa-framework-')]]" />
-\t<xsl:comment>copy the rest and add all netqa-framework actions</xsl:comment>
 \t<xsl:template match="/actions">
 \t\t<xsl:copy>
 \t\t\t<xsl:apply-templates select="@* | node()"/>
@@ -62,7 +71,7 @@ function action {
 		\t\t\t<icon/>
 		\t\t\t<name>Run with netqa-framework ($ENV_NAME)</name>
 		\t\t\t<unique-id>netqa-framework-$ENV_NAME</unique-id>
-		\t\t\t<command>exo-open --working-directory=%%d --launch TerminalEmulator "/usr/bin/env bash -c &quot;source $SHARED/$ENV_NAME/bin/activate &amp;&amp; pwd &amp;&amp; which python &amp;&amp; python %%f; deactivate&quot;"</command>
+		\t\t\t<command>exo-open --working-directory=%%d --launch TerminalEmulator "/usr/bin/env bash -c &quot;source $ENV_DIR/$ENV_NAME/bin/activate &amp;&amp; pwd &amp;&amp; which python &amp;&amp; python %%f; deactivate&quot;"</command>
 		\t\t\t<description>Run with netqa-framework (code from $ENV_NAME environment)</description>
 		\t\t\t<patterns>*.py</patterns>
 		\t\t\t<startup-notify/>
@@ -75,9 +84,16 @@ function action {
 	fi
 }
 
-SHARED=$1
-export -f action
-ACTIONS=$((cd $1 && find . -maxdepth 1 -type d) | tail -n +2 | cut -c 3- | sort | uniq | xargs -r -n 1 /usr/bin/env bash -c 'action "$@"' _)
-printf "$HEAD\n"
-printf "\t<xsl:variable name=\"custom_actions\">\n%s\n\t</xsl:variable>\n" "$ACTIONS"
-printf "$TAIL\n"
+function generate_stylesheet {
+	export -f action
+	ACTIONS=$((cd $ENV_DIR && find . -maxdepth 1 -type d) | tail -n +2 | cut -c 3- | sort | uniq | xargs -r -n 1 /usr/bin/env bash -c 'action "$@"' _)
+	printf "$HEAD\n"
+	printf "\t<xsl:variable name=\"custom_actions\">\n%s\n\t</xsl:variable>\n" "$ACTIONS"
+	printf "$TAIL\n"
+}
+
+STYLESHEET=/tmp/$($UUID_GENERATOR).xsl
+generate_stylesheet > $STYLESHEET
+$XSLT_PROCESSOR -o $THUNAR_ACTIONS_CONFIG $STYLESHEET $THUNAR_ACTIONS_CONFIG
+[ $? -ne 0 ] && die "ERROR: something went wrong, please contact the author."
+printf "INFO: Scanned %s, custom Thunar actions installed.\n" $ENV_DIR
